"on":
- push
- pull_request
name: My CI caboodle
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - v1.13.4
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./...
