on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install richgo
      run: go get -u github.com/kyoh86/richgo
    - name: Test
      run: KAFKA_DISABLE=1 richgo test -v -race -timeout=1m ./... && echo 'OK' || (echo 'FAIL' && exit 1)

